### ISSUE TITLE
Install htslib 1.2.1

### ISSUE THREAD

**Issue by oguya** [ilri/hpc-environment-modules#10]
htslib repo: https://github.com/samtools/htslib

**Comment by alanorth** [comment]
What needs this?

**Comment by oguya** [comment]
@alanorth Joyce requested for it. We ended up compiling & installing it in her home dir. Anyway, it's a good idea to install & make it available to all users.

**Comment by alanorth** [comment]
Ah, ok. Mos def then. I think I saw it yesterday as a dependency of
something else. Anyways, :+1:

On Thu, Mar 26, 2015 at 6:39 PM, James Oguya notifications@github.com
wrote:

> @alanorth https://github.com/alanorth Joyce requested for it. We ended
> up compiling & installing it in her home dir. Anyway, it's a good idea to
> install & make it available to all users.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/hpc-environment-modules/issues/10#issuecomment-86577636
> .

## 

Alan Orth
alan.orth@gmail.com
https://alaninkenya.org
https://mjanja.ch
"In heaven all the interesting people are missing." -Friedrich Nietzsche
GPG public key ID: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

**Comment by oguya** [comment]
Fixed in commit: 7b95cb70d358ef31b156d3d1396c0d02be2955d3
