### ISSUE TITLE
Update Trinity to r20140717

### ISSUE THREAD

**Issue by alanorth** [ilri/hpc-environment-modules#2]
One user was asking if we could add `util/align_and_estimate_abundance.pl` to our Trinity, but I guess this comes with newer versions, so we really just need to install the new version.

**Comment by oguya** [comment]
Seems like Trinity has moved to Github[0] & they are tagging their releases using version numbers[1] instead of release dates.

[0]. https://github.com/trinityrnaseq/trinityrnaseq
[1]. https://github.com/trinityrnaseq/trinityrnaseq/releases

**Comment by alanorth** [comment]
Awesome, I <3 GitHub. I hadn't seen that when I posted the issue last
month, but that's a great development.

**Comment by alanorth** [comment]
Compiled v2.0.3.
