### ISSUE TITLE
Update circos

### ISSUE THREAD

**Issue by oguya** [ilri/hpc-environment-modules#28]
Install the latest version of circos - `circos/0.67`[1].
1. http://circos.ca/software/download/

**Comment by alanorth** [comment]
The website was down for a bit this week, but it seems to be back up, and I see they have version `0.67-7`:
- http://www.circos.ca/distribution/circos-0.67-7.tgz

**Comment by alanorth** [comment]
Браво! Did you ever figure out how to generate a graph from the sample data?

**Comment by oguya** [comment]
yuup! I've been playing around with the tutorials -> http://www.circos.ca/documentation/tutorials/
