### ISSUE TITLE
Upgrade Bowtie2 to 2.2.5

### ISSUE THREAD

**Issue by alanorth** [ilri/hpc-environment-modules#5]
http://bowtie-bio.sourceforge.net/bowtie2/index.shtml

**Comment by alanorth** [comment]
Also, try to clean up the [bowtie wiki page](http://hpc.ilri.cgiar.org/bowtie-software) page, perhaps so we have separate pages for bowtie1 and bowtie2, and so the information is mostly for user consumption. Check out [picard](http://hpc.ilri.cgiar.org/picard-software) for example.

**Comment by oguya** [comment]
I've created two separate wiki pages for [Bowtie 1](http://hpc.ilri.cgiar.org/bowtie-software) & [Bowtie 2](http://hpc.ilri.cgiar.org/bowtie2-software).

**Comment by oguya** [comment]
Fixed in commit: 1df52fc8c8260b4d7db88f55153452b43238ff75

**Comment by alanorth** [comment]
:+1:
