### ISSUE TITLE
Install Jellyfish 2.2.0

### ISSUE THREAD

**Issue by alanorth** [ilri/hpc-environment-modules#9]
I think this is included in Trinity, but some tools like to use it on its own.

http://www.genome.umd.edu/jellyfish.html

**Comment by oguya** [comment]
Better documentation in jellyfish main repo: https://github.com/gmarcais/Jellyfish

**Comment by oguya** [comment]
Fixed in commit: 73602868e5000c310f4dde8a4072287accf59c4a
